"""Link over base on the Glade decision graph, generated by scripts/manage_decision_streams.py.

A link (GyldGrythPlugins.md section 4.4): this module imports its parent's module and
its root subclasses the parent's root, so every ruling, trigger record and question of
the chain base is inherited live. Nothing is copied, and a rebuild
of this stream follows whatever its parent says then.

Generated, not written by hand. Regenerate with:
  PYTHONPATH=src:. python3 -B scripts/manage_decision_streams.py link base rulings

gyld-stream-record:
{
  "id": "rulings",
  "kind": "link",
  "parent": "base",
  "follows": "base",
  "imports": "glade_decisions",
  "revision": "rulings@1",
  "root": "GladeDecisionsRulings",
  "note": "link of base"
}
"""

from glade_decisions import (
    BumpToCurrent,
    GladeDecisions,
    KeyCustody,
    LifecycleComposition,
    NodeTrust,
    RecoveryKeys,
    ScopeModel,
    SdaxRs,
    VersionPin,
)

from decision_stream_concepts import Decides, Ruling, Selects

from gyld import model, use


class LifecycleCompositionRuling(Ruling):
    """Confirm sdax-rs, as directed on 2026-09-12 (GDL-049). Consume it from Git pinned to an explicit rev, because lockfiles are not tracked here and an unpinned Git dependency floats; what is left to prove is async_witness.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T06:01:12Z"
    sources = ("GDL-049",)
    decides = Decides[LifecycleComposition]
    selects = Selects[SdaxRs]


class ScopeModelRuling(Ruling):
    """Node trust for the first live slice. Every node is the owner's for now, so trusting the operator costs nothing and only metadata can leak; revisit when someone else's node joins. Cryptography waits on key custody and is not a first-slice choice.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T06:01:12Z"
    sources = ("IrohGladeMapping §5.2",)
    decides = Decides[ScopeModel]
    selects = Selects[NodeTrust]


class KeyCustodyRuling(Ruling):
    """Recovery keys: recovery material is minted at first setup and kept offline. Losing every device must be survivable for a system whose point is durable data the owner controls; social recovery needs principals that do not exist yet and can be added later.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T06:01:12Z"
    sources = ("WD-1",)
    decides = Decides[KeyCustody]
    selects = Selects[RecoveryKeys]


class VersionPinRuling(Ruling):
    """Require iroh 1.2 or later in the node's manifest, done on 2026-09-21 (glade 74ffeb0): the lockfile is not tracked, so the manifest is the only place a minimum can be recorded, and the node's 61 tests pass on iroh 1.2.0. Pin each 0.x protocol crate exactly when one is first added.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T11:39:07Z"
    sources = ("IrohReview §11",)
    decides = Decides[VersionPin]
    selects = Selects[BumpToCurrent]


@model
class GladeDecisionsRulings(GladeDecisions):
    """rulings root: every member base carries, with nothing added yet."""
    lifecycle_composition_ruling = use(LifecycleCompositionRuling)
    scope_model_ruling = use(ScopeModelRuling)
    key_custody_ruling = use(KeyCustodyRuling)
    version_pin_ruling = use(VersionPinRuling)
