"""Link over base on the Glade decision graph, generated by scripts/manage_decision_streams.py.

A link (GyldGrythPlugins.md section 4.4): this module imports its parent's module and
its root subclasses the parent's root, so every ruling, trigger record and question of
the chain base is inherited live. Nothing is copied, and a rebuild
of this stream follows whatever its parent says then.

Generated, not written by hand. Regenerate with:
  PYTHONPATH=src:. python3 -B scripts/manage_decision_streams.py link base rulings

gyld-stream-record:
{
  "id": "rulings",
  "kind": "link",
  "parent": "base",
  "follows": "base",
  "imports": "glade_decisions",
  "revision": "rulings@1",
  "root": "GladeDecisionsRulings",
  "note": "link of base"
}
"""

from glade_decisions import (
    AsyncWitness,
    BindingRecord,
    BumpToCurrent,
    Dissemination,
    GladeDecisions,
    IdentityAdapters,
    KeyCustody,
    LifecycleComposition,
    NodeTrust,
    NoneInV1,
    ProofFamily,
    RecoveryKeys,
    RelayPosture,
    ScopeModel,
    SdaxRs,
    SelfHosted,
    ShakuConfirmed,
    SyncRoundOnly,
    TautGrants,
    TransportKeyBinding,
    VersionPin,
)

from decision_stream_concepts import Decides, Ruling, Selects

from gyld import model, use


class LifecycleCompositionRuling(Ruling):
    """Confirm sdax-rs, as directed on 2026-09-12 (GDL-049). Consume it from Git pinned to an explicit rev, because lockfiles are not tracked here and an unpinned Git dependency floats; what is left to prove is async_witness.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T06:01:12Z"
    sources = ("GDL-049",)
    decides = Decides[LifecycleComposition]
    selects = Selects[SdaxRs]


class ScopeModelRuling(Ruling):
    """Node trust for the first live slice. Every node is the owner's for now, so trusting the operator costs nothing and only metadata can leak; revisit when someone else's node joins. Cryptography waits on key custody and is not a first-slice choice.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T06:01:12Z"
    sources = ("IrohGladeMapping §5.2",)
    decides = Decides[ScopeModel]
    selects = Selects[NodeTrust]


class KeyCustodyRuling(Ruling):
    """Recovery keys: recovery material is minted at first setup and kept offline. Losing every device must be survivable for a system whose point is durable data the owner controls; social recovery needs principals that do not exist yet and can be added later.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T06:01:12Z"
    sources = ("WD-1",)
    decides = Decides[KeyCustody]
    selects = Selects[RecoveryKeys]


class VersionPinRuling(Ruling):
    """Require iroh 1.2 or later in the node's manifest, done on 2026-09-21 (glade 74ffeb0): the lockfile is not tracked, so the manifest is the only place a minimum can be recorded, and the node's 61 tests pass on iroh 1.2.0. Pin each 0.x protocol crate exactly when one is first added.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T11:39:07Z"
    sources = ("IrohReview §11",)
    decides = Decides[VersionPin]
    selects = Selects[BumpToCurrent]


class TransportKeyBindingRuling(Ruling):
    """A signed binding record in the node's own chain names its iroh endpoint key. The node already binds with the identity from node.key and keeps the iroh key transport-only, and recovery keys mean identity must survive a transport key being replaced; one key for both roles is simpler only until the first rotation.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T12:05:58Z"
    decides = Decides[TransportKeyBinding]
    selects = Selects[BindingRecord]


class ProofFamilyRuling(Ruling):
    """Keep the encoding our own: a chain of signed taut grants, each link signed by its parent and only ever narrowing scope, with one corpus proving Rust, TypeScript and Python agree on the bytes. Owning the format keeps the recovery rule ours to write; the cost is that no outside tool can mint or check a Glade proof, which is felt at identity_adapters.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T12:05:58Z"
    sources = ("AZ §2",)
    decides = Decides[ProofFamily]
    selects = Selects[TautGrants]


class DisseminationRuling(Ruling):
    """Sync round only. Everything runs on the owner's own nodes for now, so noticing a change at the next round costs nothing; it adds no 0.x dependency and leaves no shared topic for the node-trust metadata leak. Gossip can be added later behind the carrier port without undoing anything, since the sync round is the repair path either way; revisit when a feature across nodes needs changes to arrive faster than a round.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T12:18:45Z"
    decides = Decides[Dissemination]
    selects = Selects[SyncRoundOnly]


class IdentityAdaptersRuling(Ruling):
    """No adapter in v1: device certificates and grants made by hand, with the trust-provider interface declared and unimplemented. No user with a company directory exists yet, and each adapter is someone else's system to keep working; if one ships later it is OIDC, the one job AZ §2 left to JWT at the edge.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T12:18:45Z"
    sources = ("AZ §2",)
    decides = Decides[IdentityAdapters]
    selects = Selects[NoneInV1]


class AsyncWitnessRuling(Ruling):
    """The witness passes: DI-E01 to E04 are met on Glade's own carrier port over a real iroh endpoint, with sdax-rs owning start-up and cleanup, and the same plan run with and without Shaku does not diverge. Shaku stays at assembly only. Carried forward: every real provider in a test composition is overridden or lazy, and a provider whose close consumes its handle gives it up by value, because a leaked handle is invisible to the sdax report. The evidence is dev-docs/arch1/AsyncWitnessResult.md.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T16:03:27Z"
    sources = ("DependencyInjectionEvaluation", "GDL-048")
    decides = Decides[AsyncWitness]
    selects = Selects[ShakuConfirmed]


class RelayPostureRuling(Ruling):
    """Run our own iroh-relay for the first real route, admitting only allow-listed endpoint ids, so the only party that sees which nodes talk, from where, when and how much is us. No address lookup service for the fixed-peer slice: a peer's address is its endpoint id plus our relay's URL. If lookup is ever needed, iroh-dns-server is self-hosted too. n0's free relays never carry real data.

    Drafted by claude-fable-5-1, accepted by gianni."""
    principal = "gianni"
    stamp = "2026-09-21T16:03:27Z"
    sources = ("IrohReview §7", "GladeDiscoveryModel §5")
    decides = Decides[RelayPosture]
    selects = Selects[SelfHosted]


@model
class GladeDecisionsRulings(GladeDecisions):
    """rulings root: every member base carries, with nothing added yet."""
    lifecycle_composition_ruling = use(LifecycleCompositionRuling)
    scope_model_ruling = use(ScopeModelRuling)
    key_custody_ruling = use(KeyCustodyRuling)
    version_pin_ruling = use(VersionPinRuling)
    transport_key_binding_ruling = use(TransportKeyBindingRuling)
    proof_family_ruling = use(ProofFamilyRuling)
    dissemination_ruling = use(DisseminationRuling)
    identity_adapters_ruling = use(IdentityAdaptersRuling)
    async_witness_ruling = use(AsyncWitnessRuling)
    relay_posture_ruling = use(RelayPostureRuling)
